### ISSUE TITLE
deploy trouble

### ISSUE THREAD

**Issue by caibirdme** [ArekSredzki/electron-release-server#10]
Hey,I meet with some problems within the `local.js`
* Is it possible to use mysql to be the DB(just comment pg and add new lines of mysql in connection?)
* Do I need to learn LDAP server and develop one first?I don't know what it is...
* According to sail.js I'd better not to modify the session secret for it was generated by sails when create the app,is it OK to input a randomizedd secret? And is there any difference between seesion.secret and jwt.token_secret

I think it's a little difficult to a novice,it can't be better if there is a Dockerfile

**Comment by ArekSredzki** [comment]
Hi @caibirdme.

1. Yes, the rest of the application is adapter-agnostic. Note that you must specify the connection config name in `config/env/development.js` and `config/env/production.js`
2. You do not have to use an LDAP server, it is simply what I required for my use-case and is thus what comes available as default. You can change `api/controllers/AuthController.js` to authenticate however you like. This can be as simple as checking that the user name and password match env variables or settings specified in `local.js`.
3. This is only true if you use the sails CLI to generate an application. Since that is not what is done here, you must specify your own. The session secret is used by the server to keep track of socket.io connection sessions (to the Angular UI), while the token secret is used for generating and authenticating JWT tokens.

I understand that this isn't as portable as it could be. Any contributions in improving this would be appreciated.
