### ISSUE TITLE
Windows: Version Candidate Denied

### ISSUE THREAD

**Issue by anuprajg** [ArekSredzki/electron-release-server#116]
Just installed the latest version of the code and trying to configure the URL Feed to return the latest version. It works fine for OSX queries, but for Windows, I am always getting "Version Candidate Denied" message. I have uploaded both nupkg and exe created from the electron-builder.

Strangely, its never going into "Windows Update Search Query" but always to the "General" loop where it is expecting to find a zip. 

Something that I am missing?

**Comment by Okhoshi** [comment]
For Windows, you have to get the RELEASES file (Squirrel.Windows works differently than Squirrel.Mac). The url is the same than the one for Mac but with RELEASES at the end.

Here's the route definition for the Windows logic
https://github.com/ArekSredzki/electron-release-server/blob/master/config/routes.js#L35

**Comment by anuprajg** [comment]
oh ok, so it doesn't respond with a JSON like for Mac? What I got is a RELEASES file with some ID and a link to the nupkg file

**Comment by Okhoshi** [comment]
No, no JSON for Windows.

This is because the logic of Squirrel is different:
On Mac, this is the server that determine if an update is available.
On Windows, this logic is completely handled on the client. Technically speaking, Squirrel.Windows can be hosted as a simple file share with the RELEASES file describing the available versions, their hashes and the location of files.

**Comment by anuprajg** [comment]
Ok. Thanks for the clarification.
