### ISSUE TITLE
blockmap not found

### ISSUE THREAD

**Issue by nellyLidanYang** [ArekSredzki/electron-release-server#197]
Hi,
Can somebody tell me is this compatible with electron-updater? Or I have to use Squirrel.Windows?
I'm now using the autoupdater in electron-updater module and setFeedURL to http://127.0.0.1:1337/update/win64/ .
But I keep getting "Error: Cannot download "http://127.0.0.1/download/0.0.13/windows_64/<MyAppName>.exe.blockmap", status 404: Not Found"...
First, I do not know why there is not port in the url. The Url in setFeedURL and config file do include port 1337.
Second, how should I upload the blockmap file to the server?

I'm so frustrated and confused now

**Comment by nellyLidanYang** [comment]
And ... I have to upload .nupkg file for new versions if I want to update? Is .exe only for new install?

**Comment by devinhaughey** [comment]
Yes, this compatible with electron-update. 
The setFeedURL is just the endpoint that the Electron App queries to see if there is a new version of the software there and if so, then downloads it. When you upload the .exe file, you should also upload the latest.yml file and the blockmap file along with it under the same 0.0.13 version directory. The latest.yml file tells the application if there is a new version and then pulls it. The blockmap if I remember correctly is to check if the checksum of the files match so that nothing nefarious has occured since the compile and upload of the software.
The actual download doesn't use the setFeedURL, as you can see it uses the download/{version}/{OS}/files.
You do not need to upload the .nupkg file for updating, just the .exe file. In the latest.yml file, you will need to update some information there so that the application knows where to look for the correct version.
