### ISSUE TITLE
The default flavor has no download available

### ISSUE THREAD

**Issue by gliss** [ArekSredzki/electron-release-server#213]
When trying to do auto updates I'm getting errors on update and following through I get to this
`The default flavor has no download available for platform windows_64 for version 4.0.0-beta11_default (undefined) with
filename servapp-pointofsale-4.0.0-beta11-x64-full.nupkg with filetype .nupkg`

Breaking that down I can confirm the following exists
- version: 4.0.0-beta11_default
- platform: windows_64
- filename: servapp-pointofsale-4.0.0-beta11-x64-full.nupkg (e3c39306-952d-46b7-bf27-2387289d03e5.nupkg)

I'm not sure the undefined after version is supposed to be.

URL I'm calling is https://download.servapp.io/update/win64/4.0.0-beta.10/beta\RELEASES I then follow the link to the nupkg file.

**Comment by gliss** [comment]
Testing update after then following the link to the nupkg file **https://download.servapp.io/download/flavor/default/4.0.0-beta.10_default/windows_64/servapp-pointofsale-4.0.0-beta.10-x64-full.nupkg** (which products the above text error) if I remove the _default from the version it then works.

**Comment by DustinBrett** [comment]
I've found the issue with this. I had not properly updated this return data to match the other endpoints so it was sending version id in the URL instead of name.

Also fixed the issue with `(undefined)` being sent which is actually a pre-existing bug when channel isn't provided.

I have a [PR](https://github.com/ArekSredzki/electron-release-server/pull/215) in for these fixes.

**Comment by gliss** [comment]
Working now cheers.
