### ISSUE TITLE
how to create delta file

### ISSUE THREAD

**Issue by lzdnku307** [ArekSredzki/electron-release-server#38]
Hi:
after uploading the first version of my app,how can I build the second version to support auto-update?
it seems that auto-update need a `foo-version-delta.nupkg` file right?I found an option `win.remoteReleases` in `electron-builder` which requires `a URL to your exists updates`.I'm not sure what this exactly means.For example,I created a version 0.0.1 and upload assests `foo-0.0.1-full.nupkg` and `foo setup.exe`, and then I do some changes for my app and want to build the version 0.0.2,but I don't how to build the delta file

**Comment by caibirdme** [comment]
I have the same problem

**Comment by ArekSredzki** [comment]
Hi all,
Squirrel-Windows can handle either `-full.nupkg` files or `-delta.nupkg` files.
However, neither `electron-builder` nor `electron-release-server` support delta files. Instead, you must simply upload the `-full.nupkg` file for each release. This will be made available in the generated `RELEASES` file that your clients check, and if a new one is available, they will download and install it.

**Comment by ArekSredzki** [comment]
Don't worry about passing a url argument to `electron-builder`. That url will only be used to generate the `RELEASES` file that it outputs. However, this server doesn't use that file and generates it's own.

All you have to do is something like:
```js
let feedUrl = MY_SITE_BASE_URL + this.platform + '/' + this.currentVersion + '/' + this.channel;

autoUpdater.setFeedURL(feedUrl);
```

(electron's autoUpdater will append `/RELEASES` to that url if on windows)

**Comment by SamvelRaja** [comment]
Hi @ArekSredzki  i prefer to reopen the issue, the real problem is not on downloading the -full.nupkg file downloading while updating the app.. It is for generating the -delta.nupkg file for the next update release, which the [https://github.com/electron/windows-installer](Electron windows installer) gets as an output and downloads the full.nupkg file to generate the -delta.nupkg file. The real problem here is to keep we can't generate the -delta.nupkg file with the electron-release-server.

**Comment by ebordon** [comment]
Does [this](https://github.com/electron-userland/electron-builder/issues/1523) help you?

**Comment by Zamiell** [comment]
@ebordon That issue is about delta updates for electron-builder's `NSIS-web` auto-update scheme, which AFAIK is a completely separate auto-update scheme from Squirrel. Thus, I don't think it is applicable to this conversation.

**Comment by RyanQuackenbush** [comment]
@ArekSredzki I agree with @SamvelRaja here. I've tried config like:
```
...
"electronWinstallerConfig": {
        "remoteReleases": "http://my.release-server.domain/update/win64"
},
...
```

And get an error like

`Failed to sync URL as GitHub repo: Repo URL must be to the root URL of the repo e.g. https://github.com/myuser/myrepo`.

It seems winstaller suffixes the remoteRelease url with `RELEASES`, but the URLS returned in the downloaded `RELEASES` file (auto generated by electron-release-server) are not useable by winstaller.

Does electron-release-server support delta builds as well as delta updates? If so what URL should we use?

**Comment by ArkYk** [comment]
For those to come

The reason is Squirrel request the *-delta.nupkg file, but the *-full.nupkg file downloaded by the electron-release-server.

Check the Squirrel-Update.log in your app install folder. There are some log like below
```txt
[09/08/24 16:39:57] info: CheckForUpdateImpl: Downloading RELEASES file from http://localhost:1337/update/win64/1.0.10
[09/08/24 16:39:57] info: FileDownloader: Downloading url: http://localhost:1337/update/win64/1.0.10/RELEASES?id=yourApp&localVersion=1.0.10&arch=amd64
[09/08/24 16:39:57] info: FileDownloader: Downloading file: http://localhost:1337/download/flavor/default/1.0.11/windows_64/yourApp-1.0.11-delta.nupkg
[09/08/24 16:39:58] error: DownloadReleasesImpl: File Length should be 77539321, is 107903759
[09/08/24 16:39:58] warn: Program: Failed to apply updates, falling back to full updates: System.Exception: Checksummed file size doesn't match
```

copy 'http://localhost:1337/download/flavor/default/1.0.11/windows_64/yourApp-1.0.11-delta.nupkg' to the browser address bar. then you will get the 'yourApp-1.0.11-full.nupkg' file, not the 'yourApp-1.0.11-delta.nupkg' file.

**Comment by ArkYk** [comment]
The reason also cause the electron's autoUpdater to download twice.
