### ISSUE TITLE
Unable to get it running

### ISSUE THREAD

**Issue by limbera** [ArekSredzki/electron-release-server#6]
Hi there,

What information are we supposed to put in local.js? Why does the app need postgres etc..?

Cheers.

**Comment by ArekSredzki** [comment]
Hi @limbera

Have you looked at [the deployment documentation](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/deploy.md).

If so, specific advice on what could be improved is appreciated.

The app requires a persistent database in order to keep track of what releases are available and basic download analytics.  This project is configured to use PostgreSQL by default because that's what I used for my project here at Tesla. That said, SailsJS offers support for most databases you've ever heard of through it's ORM, Waterline (specifically the [adapters made available for it](http://sailsjs.org/documentation/concepts/extending-sails/adapters/available-adapters)).

I don't have much free time available so any improvements that you can make to the docs would be much appreciated.

**Comment by dougludlow** [comment]
@ArekSredzki I think for those of us who aren't all that familiar with sails, perhaps some links in the documentation that we can go to to help us get it configured correctly would be helpful. 

For instance, I installed postgres and finally got it working, but I don't have any sort or ldap to hook into, how do I setup basic login?

**Comment by ArekSredzki** [comment]
@dougludlow Thanks for the feedback, I'll try to find some time to do this.

As far as authentication, you're welcome to use any authentication method you please.
Again, as the result of limited time I've only provided LDAP support out of box.

You can easily replace it with your own authentication by modifying [this function](https://github.com/ArekSredzki/electron-release-server/blob/master/api/controllers/AuthController.js#L7).

**Comment by dougludlow** [comment]
@ArekSredzki thanks! I'm following this tutorial right now: http://www.geektantra.com/2013/08/implement-passport-js-authentication-with-sails-js/

**Comment by ArekSredzki** [comment]
@dougludlow Just keep in mind that most often sails authentication utilizes sessions while this app uses JWT.

**Comment by limbera** [comment]
Is there a way for it to run without any authentication or database? My application is a super simple one that has no authentication required.

**Comment by ArekSredzki** [comment]
@limbera The authentication is for the release administration interface, you can make the authentication logic as simple as you wish.

The database is definitely required. That said, look at the link I posted and it shows options for many other database adapters, including development ones such as `sails-disk` (though I do not endorse using it for any sort of production application).

**Comment by ArekSredzki** [comment]
@limbera do you have any further questions?

**Comment by limbera** [comment]
No thanks. I realise I don't need the UI so I am using nuts as you recommended.

Cheers.
