### ISSUE TITLE
OSX update URL returns nothing

### ISSUE THREAD

**Issue by PierBover** [ArekSredzki/electron-release-server#69]
According to [the docs](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/update-osx.md) this is the URL I should be calling for checking available updates:

https://updates.ascc.me/update/osx/1.1.0

Although as you can see there is no response at all. Shouldn't I be receiving a JSON or something?

I have uploaded the 1.0.0 version to the release server and have tried with different versions to see the behaviour and still get nothing.

https://updates.ascc.me/update/osx/0.0.9
https://updates.ascc.me/update/osx/0.0.1
https://updates.ascc.me/update/osx/1.0.0

Is this the correct URL?

The docs are confusing since first they suggest to use `update/osx/:version` and then the example given is `'update/'+platform+'/'+version` and platform is: `var platform = os.platform() + '_' + os.arch();`.

**Comment by ArekSredzki** [comment]
Hi Pier,

I recommend that you use Postman to look at the responses to these requests.
All of these URLs return a `204` response code and empty body, this is expected behaviour.

I see that you only have a single version uploaded, and only with `.dmg` and `.exe` assets. This is visible here: https://updates.ascc.me/api/version

Updating requires a `.zip` and `.nupkg` for OS X and windows respectively.

If you were to upload the appropriate update assets for `1.0.0` then you would get a `200` response code with some JSON for these URLs:
https://updates.ascc.me/update/osx/0.0.9
https://updates.ascc.me/update/osx/0.0.1

However, these requests would still result in a `204`:
https://updates.ascc.me/update/osx/1.0.0
https://updates.ascc.me/update/osx/1.1.0

Once you added 1.1.0 and uploaded all the appropriate assets, the following request would now return `200` with JSON
https://updates.ascc.me/update/osx/1.0.0

Looks like you're all set to do some updating, you just need the right assets & new versions to update to!

**Comment by ArekSredzki** [comment]
> The docs are confusing since first they suggest to use `update/osx/:version` and then the example given is `'update/'+platform+'/'+version`.

Feedback as to how this can be improved is welcome. That said, the two statements are consistent.

**Comment by PierBover** [comment]
Thanks a lot for the detailed info @ArekSredzki .

So what you are suggesting is that I upload an extra `.zip` file besides the `.dmg` file for the 1.0.0 release?

What should be the contents of that `.zip` file? The `.app`?

**Comment by PierBover** [comment]
> Feedback as to how this can be improved is welcome. That said, the two statements are consistent.

Well no because on the previous line `platform` returns `darwin_64` and not `osx`. Am I missing something?

**Comment by ArekSredzki** [comment]
> So what you are suggesting is that I upload an extra .zip file besides the .dmg file for the 1.0.0 release?
Yes, the `.dmg` and `.exe` are only used for initial installation, you must upload `.zip` and `.nupkg` for updating.  The `.zip` and `.nupkg` should already be a product of `electron-builder`.

**Comment by ArekSredzki** [comment]
> Well no because on the previous line platform returns darwin_64 and not osx. Am I missing something?

`electron-release-server` is pretty flexible with platform matching, `darwin`, `osx`, `osx_64` and others will all match to osx.

Note: Windows 32 and 64 bit versions are handled separately in case you wish to have both version available, so it's important to use the platform returned by node since this reflects the platform of the current binary (You wouldn't want to have the app to update itself to 64 bit from 32 bit even if your machine is 64 bit).

**Comment by PierBover** [comment]
Thanks a lot for for your help.

You were right. My `package.json` wasn't properly configured and `electron-builder` wasn't producing the `.zip` file.

So I fixed that, uploaded the `.zip` file and now it works!

https://updates.ascc.me/update/osx/0.9.0

**Comment by ArekSredzki** [comment]
Glad to hear it's working now :)
Hope you enjoy it!
