### ISSUE TITLE
Document template changes

### ISSUE THREAD

**Issue by tarjei** [ArekSredzki/electron-release-server#92]
Hi, it would be great if the app for end users (i.e. users that are not logged in) could be tuned with a few files in the config directory. As things stand, I had a hard time finding out what files I should change to get a custom look and feel for the updater - and also how to avoid doing this again when a new version is released :)

**Comment by ArekSredzki** [comment]
@tarjei Sorry for the delay.

I don't have time to update the docs right now (maybe you can submit a PR), but here is what you do.
In your fork, modify the following files to your liking:
```
/assets/styles/_variable_override.scss
/assets/js/home/home.pug
/assets/js/download/download.pug
```

Commit any changes you make to your fork.

Set up tracking of this repo as upstream:
```bash
git remote add upstream https://github.com/ArekSredzki/electron-release-server.git
```

When the upstream repo (this one) has new content that you want, you simply rebase your fork :)
```bash
git fetch upstream
git rebase upstream/master
```

Since you've rebased, you'll have to force push which is as simple as:
```bash
git push -f origin "$(git rev-parse --abbrev-ref HEAD)"
```
> Note: This generally evaluates to `git push -f origin master` here.
> If you're always on master, just use that.

**Comment by tarjei** [comment]
Thanks for answering and thanks for a great project!

I did follow this route, but it would be great if there was some sort of mechanism for overriding the templates without maintaining a fork.

Thanks again.

**Comment by ArekSredzki** [comment]
Maybe one day someone will submit a pr for it :D
